apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-application
  template:
    metadata:
      labels:
        app: microservice-application
    spec:
      containers:
        - name: microservice-application
          image: raji4ac/petclinic
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-application
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app:  microservice-application
