apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-springboot
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: microservice-springboot
  template:
    metadata:
      labels:
        app: microservice-springboot
    spec:
      containers:
        - name: springboot
          image: 407149050300.dkr.ecr.us-east-1.amazonaws.com/raji:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: microservice-springboot

