apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cloudf-spring
  namespace: cloudf-system
spec:
  gateways:
    - cloudf-gateway
  hosts:
    - app.35.188.223.63.nip.io
  http:
    - route:
        - destination:
            host: microservice-springboot
            port: 
              number: 8080

