apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata: 
  name: cloudf-gateway
  namespace: cloudf-system
spec:
  selector: 
    istio: ingressgateway
  servers:
    - hosts: 
        - app.35.188.223.63.nip.io
      port: 
        name: http
        number: 80
        protocol: HTTP

